Added spree globalize support
spree/spree_multi_vendor pull request #107
Opened 2020-04-17 15:52 UTC by drkpkg

Based in the solution from the issue response https://github.com/spree-contrib/spree_multi_vendor/issues/104#issuecomment-614384117 I added the migrations and decorators only if SpreeGlobalize is defined.

2020-04-17 16:02 UTC, damianlegawiec requested changes

2020-04-17 16:02 UTC, damianlegawiec commented on app/models/spree/vendor_translation_decorator.rb
> +::Spree::Vendor.prepend(Spree::VendorDecorator)
```suggestion
::Spree::Vendor.prepend(Spree::VendorDecorator) if defined? (SpreeGlobalize)
```

2020-04-17 16:02 UTC, damianlegawiec commented on app/models/spree/vendor_translation_decorator.rb
> +  if defined? (SpreeGlobalize)
```suggestion

```

2020-04-17 16:02 UTC, damianlegawiec commented on app/models/spree/vendor_translation_decorator.rb
> +      base.translates :name, :about_us, :contact_us, :slug, fallbacks_for_empty_translations: true
```suggestion
      if defined? (SpreeGlobalize)
        base.translates :name, :about_us, :contact_us, :slug, fallbacks_for_empty_translations: true
      end
```

2020-04-17 16:39 UTC, drkpkg reviewed
More changes :)

2020-04-17 16:56 UTC, damianlegawiec commented on app/models/spree/vendor_translation_decorator.rb
> +    Spree::Vendor.include SpreeGlobalize::Translatable
@drkpkg you can actually put this code in https://github.com/spree-contrib/spree_multi_vendor/blob/master/app/models/spree/vendor.rb

2020-04-17 16:56 UTC, damianlegawiec commented on app/models/spree/vendor_translation_decorator.rb
> +    Spree::Vendor.include SpreeGlobalize::Translatable
```suggestion
    Spree::Vendor.include SpreeGlobalize::Translatable if defined?(SpreeGlobalize)
```

2020-04-21 18:58 UTC, damianlegawiec approved these changes

2020-04-21 20:39 UTC, merged