Add text to vendor notification email
spree/spree_multi_vendor pull request #141
Opened 2020-10-21 12:18 UTC by szymoniwacz

2020-10-23 13:34 UTC, aplegatt approved these changes

2020-10-23 13:37 UTC, przemosk approved these changes

2020-10-29 12:19 UTC, damianlegawiec requested changes

2020-10-29 12:19 UTC, damianlegawiec commented on .travis.yml
> -  - gemfiles/spree_4_1.gemfile
@szymoniwacz please do not remove 4.1

2020-11-24 11:49 UTC, przemosk commented on .travis.yml
> -  - gemfiles/spree_4_1.gemfile
@damianlegawiec version `4.1` added

2022-08-04 14:06 UTC, closed without merging